name: cariddi
summary: Fast web crawler and scanner
description: |
      Take a list of domains, crawl urls and scan for endpoints, secrets, api keys, file extensions, tokens and more
version: git
grade: stable
base: core20

confinement: devmode

apps:
  cariddi:
    command: bin/cariddi
    plugs:
      - home
parts:
  cariddi:
    plugin: go
    source-type: git
    source: https://github.com/edoardottt/cariddi
